package com.f5infosol.businessbudgeter.dao.rowmapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.LinkedHashMap;
import java.util.Map;

import org.springframework.jdbc.core.RowMapper;

import com.f5infosol.businessbudgeter.domain.StaffRostersEvents;
import com.nurkiewicz.jdbcrepository.RowUnmapper;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
public class StaffRostersEventsDB
{

	private static String TABLE_NAME = "STAFF_ROSTERS_EVENTS";

	private static String TABLE_ALIAS = "sre";

	public static String getTableName()
	{
		return TABLE_NAME;
	}

	public static String getTableAlias()
	{
		return TABLE_NAME + " as " + TABLE_ALIAS;
	}

	public enum COLUMNS
	{
		SATFF_ROSTER_EVENT_ID("satff_roster_event_id"),
		EVENT_ID("event_id"),
		STAFF_ROSTER_ID("staff_roster_id"),
		STAFF_ID("staff_id"),
		ROSTER_DATE("roster_date"),
		NO_OF_HOURS("no_of_hours"),
		PUBLIC_HOLIDAY("public_holiday"),
		UPDATED_ON("updated_on"),
		UPDATED_BY("updated_by"),
		INCOME_CENTER_ID("income_center_id"),
		;

		private String columnName;

		private COLUMNS (String columnName)
		{
			this.columnName = columnName;
		}

		public void setColumnName (String columnName)
		{
			this.columnName = columnName;
		}

		public String getColumnName ()
		{
			return this.columnName;
		}

		public String getColumnAlias ()
		{
			return TABLE_ALIAS + "." + this.columnName;
		}

		public String getColumnAliasAsName ()
		{
			return TABLE_ALIAS  + "." + this.columnName + " as " + TABLE_ALIAS + "_" + this.columnName;
		}

		public String getColumnAliasName ()
		{
			return TABLE_ALIAS + "_" + this.columnName;
		}

	}

	public StaffRostersEventsDB ()
	{

	}

	public static final RowMapper<StaffRostersEvents> ROW_MAPPER = new StaffRostersEventsRowMapper ();
	public static final class  StaffRostersEventsRowMapper implements RowMapper<StaffRostersEvents>
	{
		public StaffRostersEvents mapRow(ResultSet rs, int rowNum) throws SQLException 
		{
			StaffRostersEvents obj = new StaffRostersEvents();
			obj.setSatffRosterEventId(rs.getInt(COLUMNS.SATFF_ROSTER_EVENT_ID.getColumnName()));
			obj.setEventId(rs.getInt(COLUMNS.EVENT_ID.getColumnName()));
			obj.setStaffRosterId(rs.getInt(COLUMNS.STAFF_ROSTER_ID.getColumnName()));
			obj.setStaffId(rs.getInt(COLUMNS.STAFF_ID.getColumnName()));
			obj.setRosterDate(rs.getTimestamp(COLUMNS.ROSTER_DATE.getColumnName()));
			obj.setNoOfHours(rs.getDouble(COLUMNS.NO_OF_HOURS.getColumnName()));
			obj.setPublicHoliday(rs.getBoolean(COLUMNS.PUBLIC_HOLIDAY.getColumnName()));
			obj.setUpdatedOn(rs.getTimestamp(COLUMNS.UPDATED_ON.getColumnName()));
			obj.setUpdatedBy(rs.getString(COLUMNS.UPDATED_BY.getColumnName()));
			obj.setIncomeCenterId(rs.getInt(COLUMNS.INCOME_CENTER_ID.getColumnName()));
			return obj;
		}
	}

	public static final RowUnmapper<StaffRostersEvents> ROW_UNMAPPER = new StaffRostersEventsRowUnmapper ();
	public static final class StaffRostersEventsRowUnmapper implements RowUnmapper<StaffRostersEvents>
	{
		public Map<String, Object> mapColumns(StaffRostersEvents staffrostersevents)
		{
			Map<String, Object> mapping = new LinkedHashMap<String, Object>();
			mapping.put(COLUMNS.SATFF_ROSTER_EVENT_ID.getColumnName(), staffrostersevents.getSatffRosterEventId());
			mapping.put(COLUMNS.EVENT_ID.getColumnName(), staffrostersevents.getEventId());
			mapping.put(COLUMNS.STAFF_ROSTER_ID.getColumnName(), staffrostersevents.getStaffRosterId());
			mapping.put(COLUMNS.STAFF_ID.getColumnName(), staffrostersevents.getStaffId());
			if (staffrostersevents.getRosterDate() != null)
				mapping.put(COLUMNS.ROSTER_DATE.getColumnName(), new Timestamp (staffrostersevents.getRosterDate().getTime()));
			mapping.put(COLUMNS.NO_OF_HOURS.getColumnName(), staffrostersevents.getNoOfHours());
			mapping.put(COLUMNS.PUBLIC_HOLIDAY.getColumnName(), staffrostersevents.getPublicHoliday());
			if (staffrostersevents.getUpdatedOn() != null)
				mapping.put(COLUMNS.UPDATED_ON.getColumnName(), new Timestamp (staffrostersevents.getUpdatedOn().getTime()));
			mapping.put(COLUMNS.UPDATED_BY.getColumnName(), staffrostersevents.getUpdatedBy());
			mapping.put(COLUMNS.INCOME_CENTER_ID.getColumnName(), staffrostersevents.getIncomeCenterId());
			return mapping;
		}
	}

	public static final RowMapper<StaffRostersEvents> ALIAS_ROW_MAPPER = new StaffRostersEventsAliasRowMapper ();
	public static final class  StaffRostersEventsAliasRowMapper implements RowMapper<StaffRostersEvents>
	{
		private boolean loadAllFKeys = false;
		public void setLoadAllFKeys (boolean loadAllFKeys)
		{
			this.loadAllFKeys = loadAllFKeys;
		}

		private boolean loadIncomeCentres = false;
		public void setLoadIncomeCentres (boolean loadIncomeCentres)
		{
			this.loadIncomeCentres = loadIncomeCentres;
		}

		private boolean loadEvents = false;
		public void setLoadEvents (boolean loadEvents)
		{
			this.loadEvents = loadEvents;
		}

		private boolean loadStaff = false;
		public void setLoadStaff (boolean loadStaff)
		{
			this.loadStaff = loadStaff;
		}

		public StaffRostersEvents mapRow(ResultSet rs, int rowNum) throws SQLException 
		{
			StaffRostersEvents obj = new StaffRostersEvents();
			obj.setSatffRosterEventId(rs.getInt(COLUMNS.SATFF_ROSTER_EVENT_ID.getColumnAliasName()));
			obj.setEventId(rs.getInt(COLUMNS.EVENT_ID.getColumnAliasName()));
			obj.setStaffRosterId(rs.getInt(COLUMNS.STAFF_ROSTER_ID.getColumnAliasName()));
			obj.setStaffId(rs.getInt(COLUMNS.STAFF_ID.getColumnAliasName()));
			obj.setRosterDate(rs.getTimestamp(COLUMNS.ROSTER_DATE.getColumnAliasName()));
			obj.setNoOfHours(rs.getDouble(COLUMNS.NO_OF_HOURS.getColumnAliasName()));
			obj.setPublicHoliday(rs.getBoolean(COLUMNS.PUBLIC_HOLIDAY.getColumnAliasName()));
			obj.setUpdatedOn(rs.getTimestamp(COLUMNS.UPDATED_ON.getColumnAliasName()));
			obj.setUpdatedBy(rs.getString(COLUMNS.UPDATED_BY.getColumnAliasName()));
			obj.setIncomeCenterId(rs.getInt(COLUMNS.INCOME_CENTER_ID.getColumnAliasName()));
			/*if (this.loadAllFKeys || this.loadIncomeCentres)
				obj.setIncomeCentres(IncomeCentresDB.ALIAS_ROW_MAPPER.mapRow(rs, rowNum));
			if (this.loadAllFKeys || this.loadEvents)
				obj.setEvents(EventsDB.ALIAS_ROW_MAPPER.mapRow(rs, rowNum));
			if (this.loadAllFKeys || this.loadStaff)
				obj.setStaff(StaffDB.ALIAS_ROW_MAPPER.mapRow(rs, rowNum));*/
			return obj;
		}
	}

	public static StringBuffer getAllColumnAliases ()
	{
		StringBuffer strBuf = new StringBuffer ();
		int i = COLUMNS.values ().length;
		for (COLUMNS c : COLUMNS.values ())
		{
			strBuf.append (c.getColumnAliasAsName ());
			if (--i > 0)
				strBuf.append (", ");
		}
		return strBuf;
	}

	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

}