package com.f5infosol.businessbudgeter.domain;

import java.util.Date;
import java.util.List;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.springframework.data.domain.Persistable;

/**
 * This class is generated by Spring Data Jdbc code generator.
 * 
 * @author Spring Data Jdbc Code Generator
 */
public class StaffRosters implements Persistable<Integer> {

	private static final long serialVersionUID = 1L;

	private Integer satffRosterId;

	private Integer staffId;

	private String staffName;

	private Date rosterDate;

	private String startTime;

	private String finishTime;

	private Double totalHours;

	private Boolean publicHoliday;

	private Date updatedOn;

	private String updatedBy;

	private Integer incomeCenterId;

	private transient boolean persisted;

	private IncomeCentres incomeCentres;

	private Staff staff;

	private String workofhouse;

	private String role;

	private List<StaffRostersServices> staffRostersServices;
	private List<StaffRostersEvents> staffRostersEvents;

	public List<StaffRostersEvents> getStaffRostersEvents() {
		return staffRostersEvents;
	}

	public void setStaffRostersEvents(List<StaffRostersEvents> staffRostersEvents) {
		this.staffRostersEvents = staffRostersEvents;
	}

	public StaffRosters() {

	}

	public List<StaffRostersServices> getStaffRostersServices() {
		return staffRostersServices;
	}

	public void setStaffRostersServices(List<StaffRostersServices> staffRostersServices) {
		this.staffRostersServices = staffRostersServices;
	}

	public Integer getId() {
		return this.satffRosterId;
	}

	public boolean isNew() {
		return this.satffRosterId == null;
	}

	public void setSatffRosterId(Integer satffRosterId) {
		this.satffRosterId = satffRosterId;
	}

	public Integer getSatffRosterId() {
		return this.satffRosterId;
	}

	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	public Integer getStaffId() {
		return this.staffId;
	}

	public String getStaffName() {
		return staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	public void setPublicHoliday(Boolean publicHoliday) {
		this.publicHoliday = publicHoliday;
	}

	public Boolean getPublicHoliday() {
		return this.publicHoliday;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setIncomeCenterId(Integer incomeCenterId) {
		this.incomeCenterId = incomeCenterId;
	}

	public Integer getIncomeCenterId() {
		return this.incomeCenterId;
	}

	public void setPersisted(Boolean persisted) {
		this.persisted = persisted;
	}

	public Boolean getPersisted() {
		return this.persisted;
	}

	public void setIncomeCentres(IncomeCentres incomeCentres) {
		this.incomeCentres = incomeCentres;
	}

	public IncomeCentres getIncomeCentres() {
		return this.incomeCentres;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public Date getRosterDate() {
		return rosterDate;
	}

	public void setRosterDate(Date rosterDate) {
		this.rosterDate = rosterDate;
	}

	public String getStartTime() {
		if (startTime != null && startTime.length() == 8)
			startTime = startTime.substring(0, startTime.length() - 3);
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getFinishTime() {
		if (finishTime != null && finishTime.length() == 8)
			finishTime = finishTime.substring(0, finishTime.length() - 3);
		return finishTime;
	}

	public void setFinishTime(String finishTime) {
		this.finishTime = finishTime;
	}

	public Double getTotalHours() {
		return totalHours;
	}

	public void setTotalHours(Double totalHours) {
		this.totalHours = totalHours;
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}

	public String getWorkofhouse() {
		return workofhouse;
	}

	public void setWorkofhouse(String workofhouse) {
		this.workofhouse = workofhouse;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}