package com.f5infosol.businessbudgeter.domain;

import org.springframework.data.domain.Persistable;
import org.apache.commons.lang.builder.ToStringBuilder;
import java.util.Date;

/**
 * This class is generated by Spring Data Jdbc code generator.
 * 
 * @author Spring Data Jdbc Code Generator
 */
public class StaffRostersEvents implements Persistable<Integer> {

	private static final long serialVersionUID = 1L;

	private Integer satffRosterEventId;

	private Integer eventId;

	private Integer staffRosterId;

	private Integer staffId;

	private Date rosterDate;

	private Double noOfHours;

	private Boolean publicHoliday;

	private Date updatedOn;

	private String updatedBy;

	private Integer incomeCenterId;

	private transient boolean persisted;

	private IncomeCentres incomeCentres;
	private RosterEvent events;
	private Staff staff;
	
	private boolean isEligible;
	
	

	public boolean isEligible() {
		return isEligible;
	}

	public void setEligible(boolean isEligible) {
		this.isEligible = isEligible;
	}

	public StaffRostersEvents() {

	}

	public Integer getId() {
		return this.satffRosterEventId;
	}

	public boolean isNew() {
		return this.satffRosterEventId == null;
	}

	public void setSatffRosterEventId(Integer satffRosterEventId) {
		this.satffRosterEventId = satffRosterEventId;
	}

	public Integer getSatffRosterEventId() {
		return this.satffRosterEventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	public Integer getEventId() {
		return this.eventId;
	}

	public void setStaffRosterId(Integer staffRosterId) {
		this.staffRosterId = staffRosterId;
	}

	public Integer getStaffRosterId() {
		return this.staffRosterId;
	}

	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	public Integer getStaffId() {
		return this.staffId;
	}

	public void setRosterDate(Date rosterDate) {
		this.rosterDate = rosterDate;
	}

	public Date getRosterDate() {
		return this.rosterDate;
	}

	public void setNoOfHours(Double noOfHours) {
		this.noOfHours = noOfHours;
	}

	public Double getNoOfHours() {
		return this.noOfHours;
	}

	public void setPublicHoliday(Boolean publicHoliday) {
		this.publicHoliday = publicHoliday;
	}

	public Boolean getPublicHoliday() {
		return this.publicHoliday;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setIncomeCenterId(Integer incomeCenterId) {
		this.incomeCenterId = incomeCenterId;
	}

	public Integer getIncomeCenterId() {
		return this.incomeCenterId;
	}

	public void setPersisted(Boolean persisted) {
		this.persisted = persisted;
	}

	public Boolean getPersisted() {
		return this.persisted;
	}

	public void setIncomeCentres(IncomeCentres incomeCentres) {
		this.incomeCentres = incomeCentres;
	}

	public IncomeCentres getIncomeCentres() {
		return this.incomeCentres;
	}

	public RosterEvent getEvents() {
		return events;
	}

	public void setEvents(RosterEvent events) {
		this.events = events;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Staff getStaff() {
		return this.staff;
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}

	/*
	 * START Do not remove/edit this line. CodeGenerator will preserve any code
	 * between start and end tags.
	 */

	/*
	 * END Do not remove/edit this line. CodeGenerator will preserve any code
	 * between start and end tags.
	 */

}